import type { FlowOpDefinition } from './types';

export const FLOW_OPS: FlowOpDefinition[] = [
  {
    id: 'merge',
    name: 'Merge',
    summary: 'Combine open workspace PDFs into one file.',
    impact: 'Page order follows workspace order. Bookmarks may be dropped.',
    category: 'organize',
    engines: ['pdf-lib'],
    defaultParams: {},
    paramSchema: [],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'compress',
    name: 'Compress',
    summary: 'Recompress structure; optionally use PyMuPDF for images.',
    impact: 'Not every file shrinks. Quality can drop at aggressive levels.',
    category: 'optimize',
    engines: ['pdf-lib', 'pymupdf'],
    defaultParams: { level: 'balanced' },
    paramSchema: [
      {
        key: 'level',
        label: 'Level',
        type: 'select',
        options: ['light', 'balanced', 'aggressive'],
      },
    ],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'rotate',
    name: 'Rotate',
    summary: 'Rotate selected pages by a right angle.',
    impact: 'Uses inherited pdf-lib rotation.',
    category: 'organize',
    engines: ['pdf-lib'],
    defaultParams: { angle: 90 },
    paramSchema: [
      {
        key: 'angle',
        label: 'Angle',
        type: 'select',
        options: ['90', '180', '270'],
      },
    ],
    supportsPageScope: true,
    secretKeys: [],
  },
  {
    id: 'delete-pages',
    name: 'Delete pages',
    summary: 'Drop numbered pages from the document.',
    impact: 'Cannot delete every page. Original stays in the workspace.',
    category: 'organize',
    engines: ['pdf-lib'],
    defaultParams: { pages: '' },
    paramSchema: [{ key: 'pages', label: 'Pages (1,3-5)', type: 'text' }],
    supportsPageScope: true,
    secretKeys: [],
  },
  {
    id: 'extract-pages',
    name: 'Extract pages',
    summary: 'Keep only the listed pages.',
    impact: 'Creates a smaller document. Other pages are not in the output.',
    category: 'organize',
    engines: ['pdf-lib'],
    defaultParams: { pages: '' },
    paramSchema: [{ key: 'pages', label: 'Pages to keep', type: 'text' }],
    supportsPageScope: true,
    secretKeys: [],
  },
  {
    id: 'reorder',
    name: 'Reorder pages',
    summary: 'Apply an explicit page order.',
    impact: 'Missing indexes are appended in original order.',
    category: 'organize',
    engines: ['pdf-lib'],
    defaultParams: { order: '' },
    paramSchema: [{ key: 'order', label: 'New order (1,3,2…)', type: 'text' }],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'reverse',
    name: 'Reverse pages',
    summary: 'Reverse page order.',
    impact: 'Does not rotate content.',
    category: 'organize',
    engines: ['pdf-lib'],
    defaultParams: {},
    paramSchema: [],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'remove-blank',
    name: 'Remove blank pages',
    summary: 'Drop pages that appear to have empty content streams.',
    impact: 'Heuristic. Hidden white text can look blank.',
    category: 'organize',
    engines: ['pdf-lib'],
    defaultParams: {},
    paramSchema: [],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'sanitize',
    name: 'Privacy Clean',
    summary: 'Remove metadata, scripts, attachments, and related catalog data.',
    impact: 'Honest pdf-lib pass. Rasterized secrets in images remain.',
    category: 'privacy',
    engines: ['pdf-lib'],
    defaultParams: {
      flattenForms: true,
      removeMetadata: true,
      removeAnnotations: true,
      removeJavascript: true,
      removeEmbeddedFiles: true,
    },
    paramSchema: [
      { key: 'flattenForms', label: 'Flatten forms', type: 'boolean' },
      { key: 'removeMetadata', label: 'Remove metadata', type: 'boolean' },
      { key: 'removeJavascript', label: 'Remove JavaScript', type: 'boolean' },
      {
        key: 'removeEmbeddedFiles',
        label: 'Remove attachments',
        type: 'boolean',
      },
    ],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'remove-metadata',
    name: 'Remove metadata',
    summary:
      'Clear title, author, dates, and catalog metadata this engine can see.',
    impact: 'XMP packets may still exist if not in the catalog Metadata entry.',
    category: 'privacy',
    engines: ['pdf-lib'],
    defaultParams: {},
    paramSchema: [],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'flatten',
    name: 'Flatten',
    summary: 'Flatten form fields and annotation appearances.',
    impact: 'Fields become page content and are no longer editable.',
    category: 'privacy',
    engines: ['pdf-lib'],
    defaultParams: {},
    paramSchema: [],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'remove-annotations',
    name: 'Remove annotations',
    summary: 'Delete annotation dictionaries from pages.',
    impact: 'Comments and markup are dropped, not burned in.',
    category: 'privacy',
    engines: ['pdf-lib'],
    defaultParams: {},
    paramSchema: [],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'page-numbers',
    name: 'Page numbers',
    summary: 'Draw page numbers with pdf-lib.',
    impact: 'Drawn text, not tagged structure.',
    category: 'prepare',
    engines: ['pdf-lib'],
    defaultParams: { position: 'bottom-center', format: 'page_x_of_y' },
    paramSchema: [
      {
        key: 'position',
        label: 'Position',
        type: 'select',
        options: ['bottom-center', 'bottom-right', 'top-center'],
      },
    ],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'fix-page-size',
    name: 'Normalize page size',
    summary: 'Fit pages onto a target size.',
    impact: 'May letterbox. Choose preview before export.',
    category: 'prepare',
    engines: ['pdf-lib'],
    defaultParams: { targetSize: 'A4', orientation: 'portrait' },
    paramSchema: [
      {
        key: 'targetSize',
        label: 'Size',
        type: 'select',
        options: ['A4', 'Letter'],
      },
    ],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'encrypt',
    name: 'Encrypt',
    summary: 'Password-protect the output. Password is asked at run time.',
    impact:
      'Must be last mutating step. Password is never stored in the recipe.',
    category: 'privacy',
    engines: ['qpdf'],
    defaultParams: {},
    paramSchema: [
      { key: 'password', label: 'Password (runtime)', type: 'secret' },
    ],
    supportsPageScope: false,
    secretKeys: ['password'],
  },
  {
    id: 'decrypt',
    name: 'Decrypt',
    summary: 'Open an encrypted PDF with a session password.',
    impact: 'Should run before other edits. Password is never stored.',
    category: 'privacy',
    engines: ['qpdf'],
    defaultParams: {},
    paramSchema: [
      { key: 'password', label: 'Password (runtime)', type: 'secret' },
    ],
    supportsPageScope: false,
    secretKeys: ['password'],
  },
  {
    id: 'ocr',
    name: 'OCR',
    summary: 'Add a text layer with Tesseract in the browser.',
    impact: 'Slow. Quality depends on scan resolution and language packs.',
    category: 'convert',
    engines: ['tesseract'],
    defaultParams: { language: 'eng' },
    paramSchema: [{ key: 'language', label: 'Language', type: 'text' }],
    supportsPageScope: true,
    secretKeys: [],
  },
  {
    id: 'deskew',
    name: 'Deskew',
    summary: 'Straighten scanned pages when PyMuPDF is available.',
    impact: 'No-op with a warning if the engine is not loaded.',
    category: 'prepare',
    engines: ['pymupdf'],
    defaultParams: {},
    paramSchema: [],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'pdfa',
    name: 'PDF/A attempt',
    summary: 'Best-effort PDF/A conversion via Ghostscript WASM when present.',
    impact: 'Not a claim of ISO archival compliance.',
    category: 'convert',
    engines: ['ghostscript'],
    defaultParams: {},
    paramSchema: [],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'redact',
    name: 'Redact text',
    summary: 'Permanently remove matching text with PyMuPDF when available.',
    impact:
      'Search text is never stored in the recipe. Images of words remain.',
    category: 'privacy',
    engines: ['pymupdf'],
    defaultParams: {},
    paramSchema: [
      { key: 'searchText', label: 'Text to remove (runtime)', type: 'secret' },
    ],
    supportsPageScope: false,
    secretKeys: ['searchText'],
  },
  {
    id: 'cover',
    name: 'Visual cover',
    summary: 'Draw a black rectangle. This is not redaction.',
    impact:
      'Text under the cover usually remains extractable. Proof will say so.',
    category: 'privacy',
    engines: ['pdf-lib'],
    defaultParams: { text: '' },
    paramSchema: [
      { key: 'text', label: 'Cover label (optional)', type: 'text' },
    ],
    supportsPageScope: true,
    secretKeys: [],
  },
  {
    id: 'sentinel-safe-copy',
    name: 'Sentinel Safe Copy',
    summary:
      'Sanitize active content this engine can see, then keep the original.',
    impact:
      'Uses inherited pdf-lib sanitizer. Does not prove malware-free. Rasterized secrets can remain.',
    category: 'privacy',
    engines: ['pdf-lib'],
    defaultParams: {},
    paramSchema: [],
    supportsPageScope: false,
    secretKeys: [],
  },
  {
    id: 'delete-duplicates',
    name: 'Delete duplicate pages',
    summary:
      'Drop listed duplicate pages. Never runs without an explicit page list.',
    impact:
      'Requires pages from Duplicate Finder. Original stays in the workspace.',
    category: 'organize',
    engines: ['pdf-lib'],
    defaultParams: { pages: '' },
    paramSchema: [
      { key: 'pages', label: 'Pages to drop (1,3-5)', type: 'text' },
    ],
    supportsPageScope: true,
    secretKeys: [],
  },
  {
    id: 'a11y-fix',
    name: 'Accessibility safe fix',
    summary: 'Set title and/or catalog language. Does not tag the file.',
    impact: 'Not PDF/UA or WCAG certification.',
    category: 'prepare',
    engines: ['pdf-lib'],
    defaultParams: { title: '', lang: '' },
    paramSchema: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'lang', label: 'Language (e.g. en-US)', type: 'text' },
    ],
    supportsPageScope: false,
    secretKeys: [],
  },
];

const byId = new Map(FLOW_OPS.map((op) => [op.id, op]));

export function getFlowOp(id: string): FlowOpDefinition | undefined {
  return byId.get(id);
}

export function flowOpName(id: string): string {
  return byId.get(id)?.name || id;
}
